//// Generated by spider on 2020-05-12 05:10:05.132233

class CoreAssets {
  static const String backbutton = 'assets/Core/backbutton.png';
  static const String suffixbutton = 'assets/Core/suffixbutton.png';
}
