//// Generated by spider on 2020-05-12 05:10:04.980132

class SplashScreenAssets {
  static const String background = 'assets/SplashScreen/background.png';
  static const String logo = 'assets/SplashScreen/logo.png';
  static const String splashScreenAnimation =
      'assets/SplashScreen/SplashScreenAnimation.flr';
  static const String splashScreenAnimationDark =
      'assets/SplashScreen/SplashScreenAnimationDark.flr';
}
